worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream nextjs_app {
        server nextjs:3000;
    }

    upstream minio_console {
        server minio:9001;
    }

    server {
        listen 80;
        server_name localhost;

        # -----------------------------------------------
        # 1. Rutes per defecte cap a l'aplicació Next.js
        # -----------------------------------------------
        location / {
            proxy_pass http://nextjs_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # Capçaleres obligatòries per les "Server Actions"
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # -----------------------------------------------
        # 2. Consola de gestió de MinIO (Fitxers)
        # -----------------------------------------------
        location /minio/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;

            # Websockets necessaris per MinIO
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            rewrite ^/minio/(.*) /$1 break;
            proxy_pass http://minio_console;
        }
    }
}
